"""fase9 ajustes de horas y saldo

Revision ID: 27ebe1b0b42a
Revises: 0201cd2b1d1e
Create Date: 2026-08-25 11:06:49.509395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ebe1b0b42a'
down_revision: Union[str, Sequence[str], None] = '0201cd2b1d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hour_adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hour_adjustments_adjustment_date'), 'hour_adjustments', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_hour_adjustments_approved_by'), 'hour_adjustments', ['approved_by'], unique=False)
    op.create_index(op.f('ix_hour_adjustments_employee_id'), 'hour_adjustments', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hour_adjustments_employee_id'), table_name='hour_adjustments')
    op.drop_index(op.f('ix_hour_adjustments_approved_by'), table_name='hour_adjustments')
    op.drop_index(op.f('ix_hour_adjustments_adjustment_date'), table_name='hour_adjustments')
    op.drop_table('hour_adjustments')
    # ### end Alembic commands ###
