"""fase19 qr_token unico por empleado

Revision ID: 3e6aff77cfa9
Revises: 411c447627b9
Create Date: 2026-08-27 12:27:15.270294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6aff77cfa9'
down_revision: Union[str, Sequence[str], None] = '411c447627b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Columna nullable al inicio para poder rellenar las filas existentes.
    op.add_column('employees', sa.Column('qr_token', sa.String(length=64), nullable=True))

    # Rellenar filas existentes con tokens únicos (secrets.token_urlsafe(32)).
    import secrets

    connection = op.get_bind()
    employees = connection.execute(sa.text("SELECT id FROM employees")).fetchall()
    for row in employees:
        token = secrets.token_urlsafe(32)
        connection.execute(
            sa.text("UPDATE employees SET qr_token = :t WHERE id = :id"),
            {"t": token, "id": row[0]},
        )

    # Ahora sí, obligatorio y único.
    op.alter_column('employees', 'qr_token', nullable=False)
    op.create_index(op.f('ix_employees_qr_token'), 'employees', ['qr_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_qr_token'), table_name='employees')
    op.drop_column('employees', 'qr_token')
    # ### end Alembic commands ###
