"""fase18 horas extra por tramos (politica general + override empleado)

Revision ID: 411c447627b9
Revises: 92df4e589f79
Create Date: 2026-08-27 11:23:11.379317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411c447627b9'
down_revision: Union[str, Sequence[str], None] = '92df4e589f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_overtime_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_two_hours_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('additional_hours_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('additional_hours_rate >= 35', name='ck_overtime_policy_additional_min'),
    sa.CheckConstraint('first_two_hours_rate >= 25', name='ck_overtime_policy_first_two_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('salary_settings', sa.Column('use_custom_overtime_rates', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('salary_settings', sa.Column('custom_first_two_hours_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('salary_settings', sa.Column('custom_additional_hours_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_constraint(op.f('ck_salary_fixed_rate_non_negative'), 'salary_settings', type_='check')
    op.drop_constraint(op.f('ck_salary_percentage_non_negative'), 'salary_settings', type_='check')
    op.create_check_constraint('ck_salary_custom_additional_min', 'salary_settings', 'custom_additional_hours_rate IS NULL OR custom_additional_hours_rate >= 35')
    op.create_check_constraint('ck_salary_custom_first_two_min', 'salary_settings', 'custom_first_two_hours_rate IS NULL OR custom_first_two_hours_rate >= 25')
    op.drop_column('salary_settings', 'overtime_fixed_rate')
    op.drop_column('salary_settings', 'overtime_method')
    op.drop_column('salary_settings', 'overtime_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_settings', sa.Column('overtime_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('salary_settings', sa.Column('overtime_method', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('salary_settings', sa.Column('overtime_fixed_rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint('ck_salary_custom_first_two_min', 'salary_settings', type_='check')
    op.drop_constraint('ck_salary_custom_additional_min', 'salary_settings', type_='check')
    op.create_check_constraint(op.f('ck_salary_percentage_non_negative'), 'salary_settings', 'overtime_percentage IS NULL OR overtime_percentage >= 0::numeric')
    op.create_check_constraint(op.f('ck_salary_fixed_rate_non_negative'), 'salary_settings', 'overtime_fixed_rate IS NULL OR overtime_fixed_rate >= 0::numeric')
    op.drop_column('salary_settings', 'custom_additional_hours_rate')
    op.drop_column('salary_settings', 'custom_first_two_hours_rate')
    op.drop_column('salary_settings', 'use_custom_overtime_rates')
    op.drop_table('company_overtime_policy')
    # ### end Alembic commands ###
