"""fase11 motor de payroll

Revision ID: 92df4e589f79
Revises: 27ebe1b0b42a
Create Date: 2026-08-25 11:18:54.918390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92df4e589f79'
down_revision: Union[str, Sequence[str], None] = '27ebe1b0b42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payroll_period_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('expected_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjustment_minutes', sa.Integer(), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('manual_adjustment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_records_employee_id'), 'payroll_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_payroll_period_id'), 'payroll_records', ['payroll_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_records_payroll_period_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_employee_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_table('payroll_periods')
    # ### end Alembic commands ###
