"""fase4 jornadas laborales

Revision ID: a41fb691bf12
Revises: 004a0c1cd919
Create Date: 2026-08-25 10:30:07.660921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41fb691bf12'
down_revision: Union[str, Sequence[str], None] = '004a0c1cd919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('monday_minutes', sa.Integer(), nullable=False),
    sa.Column('tuesday_minutes', sa.Integer(), nullable=False),
    sa.Column('wednesday_minutes', sa.Integer(), nullable=False),
    sa.Column('thursday_minutes', sa.Integer(), nullable=False),
    sa.Column('friday_minutes', sa.Integer(), nullable=False),
    sa.Column('saturday_minutes', sa.Integer(), nullable=False),
    sa.Column('sunday_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monday_minutes >= 0 AND tuesday_minutes >= 0 AND wednesday_minutes >= 0 AND thursday_minutes >= 0 AND friday_minutes >= 0 AND saturday_minutes >= 0 AND sunday_minutes >= 0 AND break_minutes >= 0', name='ck_work_schedule_minutes_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_schedules_employee_id'), 'work_schedules', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_schedules_employee_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    # ### end Alembic commands ###
