"""fase5 configuracion salarial

Revision ID: c22981aa3b4f
Revises: a41fb691bf12
Create Date: 2026-08-25 10:35:06.434189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22981aa3b4f'
down_revision: Union[str, Sequence[str], None] = 'a41fb691bf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('overtime_method', sa.String(length=20), nullable=False),
    sa.Column('overtime_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overtime_fixed_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monthly_salary >= 0', name='ck_salary_monthly_non_negative'),
    sa.CheckConstraint('overtime_fixed_rate IS NULL OR overtime_fixed_rate >= 0', name='ck_salary_fixed_rate_non_negative'),
    sa.CheckConstraint('overtime_percentage IS NULL OR overtime_percentage >= 0', name='ck_salary_percentage_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_settings_employee_id'), 'salary_settings', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_settings_employee_id'), table_name='salary_settings')
    op.drop_table('salary_settings')
    # ### end Alembic commands ###
