"""HST-01 carga histórica administrativa, sin alterar sesiones del kiosco.

Revision ID: l8f9a0b1c2d3
Revises: k7f8a9b0c1d2
"""
from alembic import op
import sqlalchemy as sa

revision = "l8f9a0b1c2d3"
down_revision = "k7f8a9b0c1d2"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("manual_attendance_days", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("employee_id", sa.Uuid(), nullable=False), sa.Column("work_date", sa.Date(), nullable=False), sa.Column("worked_minutes_net", sa.Integer(), nullable=False), sa.Column("normal_minutes", sa.Integer(), nullable=False, server_default="0"), sa.Column("additional_minutes", sa.Integer(), nullable=False, server_default="0"), sa.Column("recovery_minutes", sa.Integer(), nullable=False, server_default="0"), sa.Column("day_context", sa.String(24), nullable=False, server_default="ORDINARY"), sa.Column("source_reference", sa.String(200)), sa.Column("known_check_in_at", sa.DateTime(timezone=True)), sa.Column("known_check_out_at", sa.DateTime(timezone=True)), sa.Column("known_break_minutes", sa.Integer()), sa.Column("reason", sa.String(500), nullable=False), sa.Column("payment_status", sa.String(20), nullable=False, server_default="NOT_APPLICABLE"), sa.Column("payment_method", sa.String(24)), sa.Column("payment_concept", sa.String(120)), sa.Column("approved_additional_amount", sa.Numeric(12,2)), sa.Column("payment_snapshot", sa.JSON()), sa.Column("approved_by_user_id", sa.Uuid()), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("supersedes_id", sa.Uuid()), sa.Column("voided_at", sa.DateTime(timezone=True)), sa.Column("voided_by_user_id", sa.Uuid()), sa.Column("void_reason", sa.String(500)), sa.Column("created_by_user_id", sa.Uuid(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.ForeignKeyConstraint(["employee_id"], ["employees.id"]), sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"]), sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"]), sa.ForeignKeyConstraint(["voided_by_user_id"], ["users.id"]), sa.ForeignKeyConstraint(["supersedes_id"], ["manual_attendance_days.id"]), sa.CheckConstraint("worked_minutes_net >= 0 AND worked_minutes_net <= 1440", name="ck_manual_day_worked_range"), sa.CheckConstraint("normal_minutes >= 0 AND additional_minutes >= 0 AND recovery_minutes >= 0", name="ck_manual_day_parts_nonnegative"), sa.CheckConstraint("worked_minutes_net = normal_minutes + additional_minutes + recovery_minutes", name="ck_manual_day_parts_match"), sa.CheckConstraint("known_break_minutes IS NULL OR known_break_minutes >= 0", name="ck_manual_day_break_nonnegative"), sa.CheckConstraint("(known_check_in_at IS NULL OR known_check_out_at IS NULL) OR known_check_out_at >= known_check_in_at", name="ck_manual_day_known_times_order"), sa.UniqueConstraint("employee_id", "work_date", "version", name="uq_manual_day_employee_date_version"))
    for col in ("employee_id", "work_date", "approved_by_user_id", "supersedes_id", "created_by_user_id", "voided_by_user_id"): op.create_index(f"ix_manual_attendance_days_{col}", "manual_attendance_days", [col])
    op.create_index("uq_manual_day_active_employee_date", "manual_attendance_days", ["employee_id", "work_date"], unique=True, postgresql_where=sa.text("voided_at IS NULL"))
    op.create_table("recovery_commitments", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("employee_id", sa.Uuid(), nullable=False), sa.Column("permission_date", sa.Date(), nullable=False), sa.Column("agreed_minutes", sa.Integer(), nullable=False), sa.Column("covered_before", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("reference", sa.String(500), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="ACTIVE"), sa.Column("created_by_user_id", sa.Uuid(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.ForeignKeyConstraint(["employee_id"], ["employees.id"]), sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"]), sa.CheckConstraint("agreed_minutes > 0", name="ck_recovery_commitment_positive"))
    op.create_index("ix_recovery_commitments_employee_id", "recovery_commitments", ["employee_id"])
    op.create_table("manual_recovery_applications", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("manual_day_id", sa.Uuid(), nullable=False), sa.Column("commitment_id", sa.Uuid(), nullable=False), sa.Column("minutes", sa.Integer(), nullable=False), sa.ForeignKeyConstraint(["manual_day_id"], ["manual_attendance_days.id"]), sa.ForeignKeyConstraint(["commitment_id"], ["recovery_commitments.id"]), sa.CheckConstraint("minutes > 0", name="ck_manual_recovery_application_positive"), sa.UniqueConstraint("manual_day_id", "commitment_id", name="uq_manual_recovery_application"))
    op.create_index("ix_manual_recovery_applications_manual_day_id", "manual_recovery_applications", ["manual_day_id"]); op.create_index("ix_manual_recovery_applications_commitment_id", "manual_recovery_applications", ["commitment_id"])
    op.create_table("manual_attendance_idempotency", sa.Column("idempotency_key", sa.String(128), primary_key=True), sa.Column("payload_hash", sa.String(64), nullable=False), sa.Column("result", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))

def downgrade():
    raise RuntimeError("HST-01 downgrade is intentionally blocked: it would discard audited historical time")
